Fake News Classifier using Bidirectional lstm

In [14]:
import pandas as pd

In [15]:
data = pd.read_csv("data.csv")

In [16]:
data.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [17]:
data.drop(columns="date", axis=1, inplace=True)

In [18]:
data.head()

,title,text,subject,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,1

In [19]:
data.tail()

,title,text,subject,label
44893,UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...,,politics,0
44894,PM May seeks to ease Japan's Brexit fears duri...,LONDON/TOKYO (Reuters) - British Prime Ministe...,worldnews,1
44895,Merkel: Difficult German coalition talks can r...,BERLIN (Reuters) - Chancellor Angela Merkel sa...,worldnews,1
44896,Trump Stole An Idea From North Korean Propaga...,Jesus f*cking Christ our President* is a moron...,News,0
44897,BREAKING: HILLARY CLINTON’S STATE DEPARTMENT G...,IF SHE S NOT TOAST NOW THEN WE RE IN BIGGER TR...,politics,0

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   label    44898 non-null  int64
dtypes: int64(1), object(3)
memory usage: 1.4+ MB

In [21]:
data.isnull().sum()

title      0
text       0
subject    0
label      0
dtype: int64

In [22]:
data = data.dropna()

In [23]:
data.shape

(44898, 4)

In [24]:
X = data.drop('label', axis=1)

In [25]:
Y = data['label']

In [26]:
import tensorflow as tf

In [27]:
tf.__version__

'2.21.0'

In [28]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM , Bidirectional

In [29]:
### Vocab size

voc_size = 10000

One Hot Representation

In [30]:
messages = X.copy()

In [31]:
messages['title'][1]

'Trump drops Steve Bannon from National Security Council'

In [32]:
messages.reset_index(inplace=True)

In [33]:
import nltk
import re
from nltk.corpus import stopwords

In [34]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [35]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [36]:
corpus

['ben stein call th circuit court commit coup tat constitut',
 'trump drop steve bannon nation secur council',
 'puerto rico expect u lift jone act ship restrict',
 'oop trump accident confirm leak isra intellig russia video',
 'donald trump head scotland reopen golf resort',
 'paul ryan respond dem sit gun control disgust way video',
 'awesom diamond silk rip press believ video',
 'stand cheer ukip parti leader slam germani franc eu invas phoni refuge video',
 'north korea show sign seriou talk u offici',
 'trump signal willing rais u minimum wage',
 'new jersey christi mull run lead republican parti report',
 'hillari clinton spot dine alon',
 'franc germani want iran revers ballist missil program',
 'aid eu commiss head tweet pictur white smoke brexit meet may',
 'trump issu warn man armi could isi video',
 'u give lao extra million help clear unexplod ordnanc',
 'judg declar babi name illeg prevent emot harm',
 'paul ryan take monument humili photo constitu expertli troll imag',
 'republican dine trump tri railroad comey clear video',
 'u hous panel offer altern retir advis rule',
 'new poll terrif news democrat realli bad news trump',
 'boom kellyann conway school cnn anderson cooper comey fire video',
 'trump tech tycoon talk overhaul h b visa',
 'governor yemen interim capit resign accus pm corrupt',
 'u militari withstand sage grous lawmak say',
 'look like trump campaign got report arrest',
 'asian american organ rain hell upon fox news racist chinatown segment',
 'ouch bush besti goe gop elit endors trump video',
 'carter say defens relationship philippin strong',
 'factbox battl raqqa islam state syrian hq near end',
 'imag suggest north korea aggress work ballist missil submarin institut',
 'venezuela chronic shortag give rise medic flea market',
 'watch bill maher hilari thank trump expos hypocrit evangel',
 'ouch new email show hillari want fli plane michel obama',
 'china urg north korea go danger direct',
 'tennesse bill would allow counselor deni servic base religion',
 'trump say role u libya defeat islam state',
 'crookedhillari use twitter accus trump racist forget mention k donat kkk video',
 'dem senat increasingli concern trump fire mueller rosenstein stop russia probe',
 'iran sanction initi step respons provoc behavior u offici',
 'georgia governor order evacu savannah coast ahead irma',
 'whoa rush limbaugh rip republican support trump audio',
 'watch amaz thing happen h valedictorian step podium atheist group told grad could longer recit lord prayer',
 'raw video hillari bill clinton dancin gettin hampton parti',
 'trump say israel reason peac process',
 'elementari school plan black field trip colleg third grader',
 'czech parliament pick speaker open way new prime minist',
 'report corrupt wall streeter three time like go unpunish trump',
 'trump obamacar repeal boast great lesson learn',
 'russian islam state fighter sentenc hang iraq',
 'women get elect represent clinton becom presid',
 'australian pm futur safeguard crucial sydney elect',
 'treasuri mnuchin push hard u interest g offici',
 'saudi pledg million african anti jihadist forc mali',
 'philippin leader chang tune prais u alli',
 'fbi memo confirm trump told comey end russia probe attack press abhorr way',
 'watch sean hanniti fan make hilari video show destroy keurig coffe maker sean respond awesom award best video boycottkeurig',
 'exclus south sudan govern use food weapon war u n report',
 'usda disavow gag order email scientif research unit',
 'boiler room ep year anniversari extravaganza',
 'trump visit britain still unfix nine month pm may invit sourc',
 'wtf make america great hat museum case trump elect venu imag',
 'environment terrorist videotap carv quot trump golf cours green liber media call dare act defianc video',
 'dutch tourist group cut south africa visit short arm bu robberi',
 'justic depart appeal judg immigr order',
 'u disappoint india visa refus religi right panel',
 'trump sign execut order tuesday infrastructur project',
 'factbox catalonia crisi next',
 'watch veteran rip trump new one defend countri alongsid peopl hate',
 'believ conserv actual think scalia death screenshot video',
 'grab popcorn ryan bundi pretti much volunt prison',
 'lebanon hariri land cypru meet presid hariri twitter feed',
 'australian women go pro back invest boom',
 'trump tell china keep navi drone get pound unstabl',
 'kurdish leader barzani resign independ vote backfir',
 'argentin mid term campaign paus bodi found patagonia',
 'congress fund detent bed despit drop border cross',
 'whoa hillari pull mitt romney may recov one audio',
 'blumenth ask antitrust pick discuss white hous role deal',
 'wealthi man pass away leav million open ohio anim shelter',
 'watch chri wallac nail trump tout job report call phoni',
 'video obama letterman ignor pocket poverti obama stimulu gave billion baltimor',
 'race obsess democrat congressman caught allow daughter use vehicl congression plate taxi hire',
 'tillerson asia trip seen produc concret action north korea state dept',
 'isra minist say trump speech may start war iran',
 'meet trump case miss barbara walter exclus interview trump video',
 'hous committe launch review fda crimin offic',
 'patriot owner trump toughest time life belov wife die call week year ya video',
 'watch giuliani big lie trump ralli jaw drop',
 'u n brace rohingya flee seek access rakhin myanmar',
 'mueller impanel washington grand juri russia probe wall street journal',
 'hack commi georg soro hack dc leak',
 'comedian margaret cho compar donald trump roman emperor nero',
 'macron idea bolster franco german axi merkel',
 'stun admiss john mccain hand democrat senat audio',
 'u tax bill may face lawsuit long odd polit payoff',
 'john oliv cat creat intern incid video',
 'wow trump help hillari see first big crowd want miss video',
 'sign pace slow third week obamacar enrol',
 'trump tri launch elect ad immedi blow face tweet',
 'jerusalem decis creativ chao effect turmoil',
 'syrian armi iranian back militia push toward idlib provinc',
 'penc say nafta renegoti win win win',
 'trump health pick favor insur peopl prior ill',
 'watch trump absolut crush wife viral video clip inaugur',
 'turkey suspend non immigr visa servic diplomat facil u',
 'watch last week giant odel beckham jr peed field rais black power fist kneel nation anthem today left field cri like babi',
 'graft suspect indonesian anti corrupt monument project',
 'famili valu republican bust sex video govern comput',
 'uk lawmak vent anger pm may fragil govern welfar reform',
 'lose immun german anti immigr parti co head may face perjuri charg',
 'ucla basketbal player arrest china ahead trump visit report',
 'lol lifetim politician got support voter gop primari tell cb know america first mean video',
 'putin say doubt trump met moscow prostitut',
 'white wash trump claim classifi jfk file releas reignit conspiraci suspicion',
 'china say handl north korea trade issu benefit peac stabil',
 'boat carri asylum seeker myanmar capsiz bangladesh',
 'man said recess great recess rumor top econom post',
 'putin say stronger russia china tie major boon everyon',
 'arab europ u n reject trump recognit jerusalem isra capit',
 'saudi arabia say dismantl islam state cell riyadh',
 'trump spoke fate ucla basketbal player detain china video',
 'cover mugab reuter one say die',
 'trump critic gm mexico invest',
 'britain want zimbabw rejoin intern commun pm may',
 'honduran vote count give hernandez point lead rival',
 'video sicken challeng goe viral disrespect american flag stomp',
 'trump meet germani angela merkel goe awkward offens second video',
 'republican propos delay paus obamacar tax',
 'clinton express concern time warner deal',
 'u launch opioid fraud detect unit',
 'itali govern win confid vote contest elector law',
 'watch mexican american trump support destroy liber ca citi council member problem liber lay claim help minor rare help',
 'poll show hillari lead trump surpris demograph first time ever',
 'octob teas wikileak fals start leav trump support sleepless exasper',
 'oppon saudi bill keep fight ahead veto overrid vote',
 'exclus pyongyang univers start fall class without american staff travel ban',
 'judg napolitano reckless hillari email could respons death cia fbi agent video',
 'watch gop senat yawn disabl healthcar protest drag away cop',
 'zimbabw mugab defi expect immedi resign',
 'veteran letter thank berni sander vote iraq war goe viral video',
 'wow even cnn report mueller new russian investig hire made major contribut hillari barack schumer campaign',
 'republican u health plan clear first hurdl fate uncertain',
 'watch beyonc perform sicken cop hate anti white song super bowl',
 'watch nra presid obama come',
 'trump say mexico taken advantag u long enough',
 'former cia director reveal putin recruit trump doubl agent',
 'britain may say set red line minist behavior',
 'amid opposit trump make low budget request mexico border wall',
 'uk johnson iran talk lobbi jail aid worker',
 'uk pm may hold bilater meet trump g uk govt offici',
 'tillerson visit africa first quarter advis',
 'bulgarian macedonian orthodox church edg closer despit thorni histori',
 'obama deliv statement economi white hous',
 'fiat chrysler readi compli new rule trump administr ceo',
 'pakistani taliban say behind deadli blast tribal region',
 'trump campaign releas tax return republican vp nomine penc',
 'giuliani pull consider serv administr trump',
 'believ california governor desper move help elect hillari',
 'adel break best album grammi award half stage give embarrass white guilt apolog speech deserv beyonc way make black friend feel video',
 'mexico presidenti hope hem rule parti legaci',
 'spectacular leftist media melt realiz america buy lie elect trump anyhow video',
 'russia lavrov iran zarif moscow commit iran nuclear deal',
 'wow berkeley mayor allegedli told polic stand part antifa terrorist facebook group',
 'ten million australian vote far sex marriag poll',
 'venezuela ex prosecutor say evid maduro corrupt',
 'watch senat elizabeth warren laugh trump pathet attempt insult',
 'israel hail trump histor declar palestinian condemn',
 'hillari vp nomine pander black done apolog slaveri',
 'pro busi parti tri hem german green red line',
 'trump tap ex labor board member acosta labor secretari',
 'donor terrifi trump beg gop find rd parti candid sabotag',
 'six ugandan mp eject rowdi debat extend rule age museveni',
 'dem senat blast mitch mcconnel exclud women panel draft new senat health plan',
 'mladic still hero die home villag bosnia',
 'chicago polic say tell trump cancel uic ralli video',
 'wisconsin governor back republican ted cruz presidenti race',
 'hillari take credit arab spring disast want presid',
 'nail nigel farag say american think pathet hillari clinton video',
 'obama sign defens spend bill critic guantanamo polici',
 'realli want miss ana navarro pummel trump chief racism apologist video',
 'trump slam obama vow undo cuban polici',
 'sicken soro protest block u air forc vet enter inaugur ceremoni video',
 'jame comey bombshel pre testimoni statement',
 'stop whine u elect rig obama tell trump',
 'break feder judg stop obamacar transgend abort relat protect',
 'heartbroken woman tear boston antifa assault watch america destroy video',
 'u work other deni north korea fuel suppli tillerson',
 'u back sdf let syrian islam state fighter leav raqqa',
 'disturb video show hillari campaign like fake audienc nc ralli',
 'canada propos health warn child proof pack legal pot sale',
 'obama say stay washington leav white hous usa today',
 'jare kushner excus russian meet would get peopl fire',
 'u hous may consid bill fund govern week sourc',
 'saudi princ lectur america democraci call never trump',
 'russia say u iran sanction undermin nuclear deal',
 'new york citi ad campaign support transgend bathroom right',
 'leftist media destroy mike flynn crack joke horribl lie obama nation secur advisor told media famili benghazi victim video',
 'woman defend gop sexism charg year quit parti epic twitter storm',
 'smaller eu state need stronger voic brussel say czech elect favorit',
 'obama deliv statement economi tuesday invers move',
 'ukrain poroshenko suggest imf back anti graft court take time',
 'trump directli beg twitter fan money unpreced desper tweet',
 'racist lose mind mexican american teen sing nation anthem dem debat tweet',
 'court say republican gerrymand wisconsin unconstitut',
 'fbi clinton foundat investig lead like indict donor fund isi',
 'yemen houthi say sanaa airport repair readi receiv flight agenc',
 'democrat senat wyden say vote puerto rico debt bill',
 'roll stone demand trump stop use music imagin presid trump worst nightmar',
 'china say one step forward two step back good japan tie',
 'congress vote call trump denounc hate group',
 'oop cdc employe sick deal influx illeg minor send email obama worst prez ever marxist',
 'mn somali muslim immigr explain accept kill anyon insult moham video',
 'chang tune man polic van freddi gray break silenc',
 'ex marin chosen direct u extradit effort',
 'report black women becom educ group u video',
 'far right score surpris success czech elect',
 'mexico cut share refin sugar sent u minist say',
 'brutal truth benghazi hour home sale blow right elect hillari want gone video',
 'trump receiv multipl option iran nuclear deal tillerson',
 'angri mark levin write letter cnn anchor brian stelter thoroughli dishonest',
 'fox news help domest terrorist',
 'factbox republican u senat watch debat tax bill',
 'reinc priebu back trump claim media enemi video',
 'catalan standoff touch separatist heart beyond spain',
 'u presidenti first trump pray jerusalem western wall',
 'hungari jobbik parti say fine risk make insolv ahead vote',
 'first visit trump urg reform u n meet full potenti',
 'ha believ hillari luxuri scoobi van',
 'video law hillari campaign van caught go mph zone',
 'anoth white trump support assault black man terrifi ralli south video',
 'high school start cave trump punish athlet stand nation anthem',
 'panama send immigr envoy china visa limit lift',
 'virginia republican goodlatt seek elect',
 'bundi terrorist left malheur refug video',
 'violent protest outsid trump ralli pittsburgh cop come black live matter thug video',
 'obama hold final press confer wednesday white hous',
 'debbi wasserman schultz accus obama dh director jeh johnson lie oath video',
 'trump support storm maxin water town hall demand entri deni let us video',
 'oregon fed cover foul play finicum death fed shell case gone miss',
 'virginia paper troll gov pat mccrori hard endors elect',
 'cop ask mayor remov black live matter banner hang citi hall respons astound',
 'watch violent trump fan shove peac protest stair behind like coward',
 'gop rep dave brat humili msnbc host craig melvin liber media bia make melvin wish never interview video',
 'cnn lemon tri downplay horrif anti trump tortur mental disabl man',
 'liber hack alec baldwin perform rank trump bash skit last night baldwin saint',
 'trump meet tech giant everybodi room like video',
 'hillari clinton blast steve king blatant racism liter white supremaci',
 'main gop state senat sick bullsh demand censur governor paul lepag',
 'democrat senat schumer trump stop blame puerto rican',
 'globalist commi bill de blasio abandon nyc g protest phoni de blasio aka warren wilhelm jr get touch german root',
 'obama new improv fbi offer huge reward anyon help frame white cop black thug shoot',
 'oklahoma lawmak found boy motel charg prostitut',
 'late night host new york citi utterli crucifi ted cruz video',
 'ahead debat trump endors bush alumni',
 'exclus u budget plan includ billion new submarin sourc',
 'trump campaign majorli f ck accident email anti clinton strategi journalist',
 'lol democrat cheerlead coki robert deliv devast news abc comrad go hard defeat roy moor trump endors video',
 'clinton foundat health project still mull foreign donat',
 'trump son law kushner congression statement',
 'u air forc run bomb drop isi worri though barri got',
 'kansa governor tap religi ambassador reflect legaci',
 'briton plead guilti weapon charg trump ralli incid',
 'video water war obama epa power grab regul puddl pond anyth wet',
 'drain swamp republican run elect',
 'u warn sanction countri trade north korea',
 'wall street wisconsin broker cheer trump order',
 'fire woman rant nyu professor goe apesh cop protest f ck nypd video',
 'trump urg nation isol north korea brutal regim south korea speech',
 'donald trump tri spin second amend threat get destroy twitter',
 'finland want eu give daylight save time',
 'franc macron seek renew africa tie old problem persist',
 'trump indic wh previous lie second secret putin meet small talk',
 'john kerri commit u militari aid ex soviet georgia',
 'oh boy target custom respond new gender neutral toy label',
 'bombshel report show russian meet noth burger',
 'cuba visit colorado governor see govern desir work trump',
 'senat collin say commit tax bill concern salt',
 'distrust u alli forc spi agenc back encrypt fight',
 'comey say trump fire undermin fbi russia investig',
 'white hous make decis report june bob graham',
 'secretari state shannon meet tillerson u offici',
 'democrat threaten kid educ chicago teacher union demand rais chicago public school run money one week',
 'hillari clinton realli break toe video',
 'philippin presid say south china sea row better left untouch',
 'n dakota legisl propos bill protect motorist hit pipelin protest intent block road',
 'guatemala prosecutor raid millicom offic graft probe',
 'religi liberti bill pass georgia state legislatur',
 'elit nazi alli order hungari claim trump advis sebastian gorka sworn member',
 'itali govern win five confid vote elector law',
 'conserv mom cruz support goe trump',
 'communist georg soro say trump win popular vote landslid hillari win presid huh video',
 'second twin fall sexual assault case moham hussein eldai face feloni charg sexual assault mental retard woman',
 'ex u spi chief urg congress renew internet surveil law',
 'brazil struggl help state depend venezuela power',
 'venezuela maduro thank putin support difficult time',
 'state dept releas clinton e mail white hous refus releas import one',
 'ex alli malaysian pm najib held graft probe sourc',
 'gop ex gov new jersey attack christi endors trump vote blue win',
 'hous vote protect dark money polit donor',
 'obama turn focu u congress campaign clinton',
 'wow fbi su andrew breitbart record request withhold',
 'bill reilli play stump trump foreign polici make look like fool video',
 'trump first year offic mark controversi protest',
 'watch highli anticip clinton cash movi free thank breitbart',
 'yemeni al qaeda leader call attack support myanmar rohingya',
 'women march one peac demonstr american histori',
 'trump meet congression leader next week legisl issu white hous',
 'polish presid sign judici overhaul bill law',
 'south korean support nuclear project deal blow govern energi plan',
 'cruz make baffl bestial joke trump mark new low point campaign',
 'sara carter uncov explos evid violat american civil liberti obama video',
 'iraq oil ministri warn oil compani kurdistan contract',
 'trump billion china miracl add gloss kilter trade',
 'obama tell trump stop whine rig elect claim',
 'bill maher barney frank destroy gop choos petti polit function suprem court',
 'china accus australia paranoia foreign influenc law',
 'egyptian air forc strike arm convoy libyan border',
 'embarrass view angri femi nazi match trump brilliant femal campaign manag video',
 'never guess new york time blame north korea decad long famin',
 'explain result beaten angola parti head tell elector commiss',
 'obama say china would take chang u polici taiwan lightli',
 'australian former governor gener peacemak ninian stephen die',
 'republican may gener less heat miami debat',

In [37]:
one_hot_repr = [one_hot(words, voc_size) for words in corpus]
one_hot_repr

[[2833, 9966, 9547, 2213, 8509, 5687, 1454, 2979, 4162, 2979],
 [7285, 6873, 9436, 3186, 9169, 49, 9182],
 [6961, 9636, 8126, 8331, 7710, 8574, 6852, 8171, 7452],
 [9850, 7285, 3044, 1766, 1783, 4995, 3629, 2905, 1613],
 [5555, 7285, 5981, 9597, 6407, 7549, 3128],
 [783, 2307, 7630, 5822, 1450, 5666, 6694, 960, 3616, 1613],
 [2090, 6434, 9437, 6776, 2218, 3178, 1613],
 [8684, 8818, 1067, 998, 6989, 3923, 7560, 3331, 9081, 6667, 8004, 6199, 1613],
 [1819, 7622, 8152, 7179, 131, 7166, 8331, 5453],
 [7285, 5223, 1435, 349, 8331, 3501, 3386],
 [5989, 3876, 4788, 7771, 56, 6088, 5320, 998, 1813],
 [2470, 2032, 5434, 7278, 7032],
 [3331, 7560, 6670, 3995, 4682, 7382, 4601, 2467],
 [4156, 9081, 7545, 5981, 79, 711, 9563, 1708, 9168, 2825, 8624],
 [7285, 8507, 4626, 3771, 8360, 2100, 1936, 1613],
 [8331, 1998, 8307, 428, 2466, 1157, 4315, 3398, 4745],
 [4264, 8796, 6442, 2356, 4883, 756, 3327, 1579],
 [783, 2307, 866, 4031, 4212, 2504, 1498, 5085, 3290, 6419],
 [5320, 7278, 7285, 3157, 2420, 7167, 4315, 1613],
 [8331, 907, 9141, 113, 9268, 7309, 6645, 9138],
 [5989, 279, 4475, 5436, 8912, 8524, 1482, 5436, 7285],
 [7001, 4033, 4623, 8320, 542, 7329, 3181, 7167, 2350, 1613],
 [7285, 1397, 7189, 7166, 9847, 5791, 4396, 9713],
 [8520, 6493, 8056, 809, 1702, 5574, 9259, 1146],
 [8331, 4037, 9138, 7026, 2653, 1849, 1487],
 [9585, 9170, 7285, 9748, 5903, 1813, 489],
 [9688, 9451, 6995, 5351, 5235, 8890, 5674, 5436, 8809, 8266, 4793],
 [5707, 1762, 7307, 5128, 3008, 3670, 7734, 7285, 1613],
 [4079, 1487, 3093, 2169, 2649, 9119],
 [4910, 7163, 5919, 1562, 2580, 756, 8281, 7370, 949],
 [6419, 464, 1819, 7622, 4853, 1872, 7382, 4601, 8936, 4827],
 [499, 5158, 7915, 1998, 3666, 8155, 654, 5211],
 [2184, 9415, 3541, 8892, 9212, 7285, 962, 1393, 8450],
 [5707, 5989, 7463, 8152, 2470, 6670, 1187, 2434, 2173, 6072],
 [7185, 1352, 1819, 7622, 3288, 967, 4577],
 [8605, 9415, 266, 6414, 4949, 1274, 4333, 9956, 957],
 [7285, 1487, 1394, 8331, 9468, 1150, 1562, 2580],
 [3325, 4358, 7196, 5574, 7285, 8809, 5943, 5519, 720, 2821, 9784, 1613],
 [5822, 3975, 8309, 7963, 7285, 2350, 608, 9999, 534, 2905, 303],
 [3995, 8353, 369, 2394, 4379, 4587, 8028, 8331, 5453],
 [7036, 8520, 2893, 6050, 5443, 6902, 1016, 4170],
 [9133, 9478, 8913, 6776, 5320, 8715, 7285, 214],
 [2184,
  4546,
  6870,
  3291,
  5791,
  8720,
  2394,
  5955,
  653,
  2476,
  9726,
  8613,
  2100,
  3707,
  7186,
  7511,
  6900],
 [9319, 1613, 2470, 9415, 2032, 4, 3162, 7105, 998],
 [7285, 1487, 697, 9301, 9829, 726],
 [7118, 8320, 113, 7656, 820, 84, 4770, 1170, 7964],
 [8014, 9544, 4505, 493, 6400, 3616, 5989, 1232, 5378],
 [1813, 1146, 3352, 8873, 8580, 3141, 9170, 3288, 3806, 7285],
 [7285, 4320, 6976, 7412, 6507, 3691, 1570],
 [4774, 1562, 2580, 1014, 1944, 2127, 7674],
 [820, 2239, 3401, 3033, 2032, 9383, 6750],
 [6024, 9259, 350, 6127, 5497, 3615, 3401],
 [9310, 8897, 8979, 7762, 8331, 4965, 1397, 5453],
 [9328, 9267, 2466, 9692, 1050, 6065, 5723, 7586],
 [2649, 6989, 5713, 8425, 5905, 8331, 2726],
 [2884, 1922, 1766, 7285, 9726, 7167, 949, 2905, 303, 8562, 2218, 7555, 3616],
 [2184,
  6898,
  8182,
  485,
  4620,
  8892,
  1613,
  8152,
  5626,
  2098,
  4680,
  6032,
  6898,
  7630,
  2090,
  4895,
  6512,
  1613,
  5112],
 [4885, 7297, 6906, 177, 4358, 4803, 9821, 8663, 8331, 823, 1813],
 [5238, 1158, 5293, 2893, 7463, 8039, 602, 3580],
 [785, 9023, 9859, 4063, 8505, 8689],
 [7285, 5019, 4754, 5082, 1, 417, 6393, 9259, 8624, 7716, 8208],
 [2531, 4620, 1311, 6507, 8925, 8879, 7675, 7285, 3401, 1365, 6419],
 [2316,
  2711,
  2338,
  5014,
  9895,
  7285,
  7549,
  786,
  9352,
  4080,
  3277,
  9547,
  833,
  6852,
  7787,
  1613],
 [4167, 6508, 2476, 108, 7297, 2254, 5019, 8986, 4448, 5439, 8424],
 [3415, 712, 4672, 4264, 4424, 2893],
 [8331, 8105, 1569, 9713, 4661, 8903, 2130, 9141],
 [7285, 7179, 4784, 2893, 971, 2996, 6652],
 [4910, 3435, 8567, 3439],
 [2184, 5670, 6776, 7285, 5989, 985, 5992, 8761, 1242, 6001, 4691],
 [3178, 7314, 5231, 6861, 8868, 3073, 3103, 1613],
 [6490, 5572, 2307, 7738, 771, 1961, 9936, 7886],
 [5526, 9530, 7324, 3951, 2825, 6750, 9530, 7196, 4400],
 [6024, 820, 3288, 1003, 918, 4872, 7001],
 [7285, 6409, 7185, 6211, 3865, 4249, 2239, 4835, 7893],
 [7079, 6989, 165, 1702, 8733, 2697, 8390],
 [5273, 710, 8657, 9748, 3936, 3775, 5135, 6421],
 [2538, 7159, 763, 9811, 4379, 6873, 6799, 1632],
 [9133, 2470, 7113, 141, 9015, 8624, 7820, 985, 214],
 [2853, 4370, 1706, 4505, 1904, 9563, 907, 1394, 6181],
 [1632, 3771, 8121, 5715, 8741, 2466, 6400, 2542, 5078, 209],
 [2184, 3534, 1089, 2380, 7285, 254, 2890, 1813, 9547, 8004],
 [1613, 6072, 3784, 3621, 3544, 4988, 6072, 7107, 4978, 6432, 8640],
 [8575,
  4518,
  8912,
  9433,
  9909,
  6414,
  2024,
  4358,
  5340,
  6474,
  6203,
  1147,
  9881],
 [2865, 337, 84, 7993, 6592, 383, 4965, 1819, 7622, 2580, 7837],
 [4995, 5378, 1487, 7285, 9976, 8624, 6898, 8663, 3995],
 [2825, 7285, 7675, 7738, 292, 2070, 4885, 182, 7285, 1613],
 [907, 2248, 8242, 2134, 9062, 5683, 2612],
 [2063,
  6564,
  7285,
  671,
  3141,
  2680,
  6569,
  1928,
  7607,
  9547,
  3143,
  4063,
  1082,
  1613],
 [2184, 2673, 4653, 5590, 7285, 7212, 6386, 6873],
 [8331, 823, 3901, 842, 7603, 594, 7227, 3048, 1267],
 [608, 1237, 4604, 3279, 8098, 2905, 303, 3352, 9309, 1703],
 [7763, 5532, 1209, 1327, 7763, 4184, 1783],
 [482, 3106, 166, 9318, 5555, 7285, 7066, 7104, 1591],
 [3222, 1861, 1064, 5313, 9263, 3028, 6330],
 [546, 3585, 3857, 4449, 1350, 8912, 3975, 214],
 [8331, 2850, 9415, 8624, 3320, 6618, 3567, 1115, 6382, 5046],
 [3857, 3259, 5889, 2519, 5264, 7335, 1613],
 [1646, 7285, 1157, 2470, 5493, 9281, 4653, 5220, 6670, 7738, 1613],
 [7179, 687, 5603, 1170, 3143, 4320, 2708],
 [7285, 3157, 8242, 3401, 3030, 1004, 7736, 3320, 79],
 [1019, 1163, 7918, 3016, 2489, 2360],
 [756, 8360, 6349, 918, 1099, 8979, 5636, 6694, 7407],
 [7039, 1487, 3441, 6955, 7561, 7561, 7561],
 [7285, 9817, 4505, 581, 7673, 6001, 7104, 4212],
 [2184, 7285, 9696, 9324, 1928, 9478, 1613, 9432, 9310],
 [8747, 6497, 2802, 4424, 9713, 4333, 4098, 8264, 8331],
 [2184,
  3165,
  3143,
  8416,
  5653,
  7260,
  8124,
  9300,
  820,
  349,
  7656,
  7635,
  5162,
  7124,
  9169,
  1571,
  6988,
  299,
  820,
  3853,
  9170,
  6442],
 [5192, 1157, 2583, 1050, 1146, 4031, 6652],
 [7528, 9809, 5320, 6392, 3346, 1613, 177, 5804],
 [6866, 1849, 5517, 5186, 9259, 8624, 1624, 177, 8371, 9798],
 [163, 7206, 9263, 1050, 4424, 998, 7752, 5981, 8624, 3320, 1776, 5764],
 [2337, 6105, 7073, 489, 7185, 1016, 7285, 5019, 1813],
 [2117,
  8807,
  1683,
  5903,
  8715,
  9898,
  3008,
  5855,
  6409,
  595,
  4258,
  1311,
  9281,
  7089,
  1613],
 [4277, 1487, 3714, 7285, 7719, 549, 1514],
 [9563, 2228, 7285, 8756, 4703, 2528, 347, 5269, 8569, 3140, 8629],
 [7185, 1487, 5662, 1819, 7622, 3655, 8507, 7462, 9829, 4157],
 [6795, 8705, 1921, 8123, 1267, 3520, 8637],
 [3771, 4646, 345, 6507, 345, 7087, 8757, 1711, 1033],
 [4277, 1487, 5733, 2905, 7185, 7370, 803, 7702, 9854],
 [4895, 8600, 8331, 823, 8606, 7285, 6061, 1019, 4995, 809],
 [9328, 5390, 1487, 4398, 1562, 2580, 6761, 1952],
 [7285, 8995, 4229, 2337, 6105, 7073, 8913, 7185, 1613],
 [328, 8473, 6602, 985, 1487, 7607],
 [7285, 1589, 5369, 637, 4872],
 [4754, 6670, 5412, 4263, 5264, 8670, 9259, 8624],
 [401, 2697, 454, 1998, 4576, 7116, 6088, 1964],
 [1613, 3381, 2748, 5128, 9478, 2608, 9451, 7498, 1823],
 [7285, 2825, 7560, 5511, 6330, 5128, 4472, 5213, 7168, 1613],
 [5320, 6186, 6114, 3936, 4320, 2850],
 [2032, 3485, 7963, 3141, 8047, 6181],
 [8331, 8242, 410, 2949, 1611, 3580],
 [6080, 177, 7561, 6875, 2697, 9529, 2489, 200],
 [2184,
  1088,
  9451,
  7285,
  8715,
  5626,
  4080,
  5539,
  3499,
  9182,
  2396,
  5816,
  4080,
  5449,
  8756,
  1157,
  4962,
  7567,
  1157],
 [279, 8152, 2470, 6088, 7285, 584, 9470, 9281, 3141, 3924],
 [2278, 3305, 3123, 3309, 6898, 8741, 7285, 8715, 2576, 2182],
 [6958, 9328, 9415, 6211, 5152, 1016, 5581, 1119, 2697],
 [4885, 7292, 7785, 6898, 9790, 7855, 1605, 9451, 5200, 8871, 2603],
 [4264, 4718, 6036, 2470, 7463, 2100, 4379, 3073, 2444, 2884, 8748, 1613],
 [2184, 3008, 3975, 54, 8287, 9197, 3581, 5193, 5715, 3647],
 [5412, 8473, 5188, 8126, 1004, 1702],
 [5670, 4969, 9212, 7360, 6952, 2697, 7674, 8663, 5128, 9478, 1613],
 [1646,
  1219,
  542,
  1813,
  608,
  5989,
  4774,
  5329,
  9881,
  4983,
  803,
  5937,
  2470,
  9003,
  2119,
  9748],
 [5320, 8331, 9817, 113, 4315, 9281, 9290, 4229, 5143],
 [2184, 3669, 2352, 3381, 3647, 4691, 1050, 9563, 8322, 989, 5689],
 [2184, 5012, 6750, 6072, 4975],
 [7285, 1487, 637, 7097, 8097, 8331, 3567, 3420],
 [560, 2444, 771, 7539, 4277, 7943, 7285, 108, 8748],
 [4754, 8624, 1487, 2933, 802, 2402, 5378, 8028],
 [3507, 8757, 7285, 4620, 7800, 8786, 6004, 637, 6799, 3352],
 [6866, 9584, 3995, 7166, 7233, 7434, 4156, 3354],
 [6866, 9259, 8624, 2035, 6444, 2825, 7285, 1397, 6866, 1731, 5453],
 [2865, 5019, 2254, 9281, 6516, 6645],
 [3097, 5070, 8788, 1521, 3215, 8279, 4379, 9227, 5860],
 [6072, 5659, 8131, 6396, 9563, 907],
 [3975, 286, 4974, 668, 5989, 9138, 7285, 1969, 7673],
 [9733, 7469, 1487, 2132, 8278, 745, 960, 1960],
 [7285, 9748, 5269, 2850, 8425, 5320, 6230, 7661, 7039],
 [2673, 7113, 2957, 7730, 1969, 7285],
 [3178, 9323, 8520, 6489, 1470, 1157, 3401, 2470],
 [7184,
  9296,
  6512,
  7370,
  5558,
  4895,
  8918,
  5660,
  1998,
  6500,
  9563,
  3818,
  7345,
  9976,
  3596,
  3669,
  3616,
  4620,
  7656,
  1028,
  1829,
  1613],
 [637, 4492, 4344, 5115, 9138, 998, 4049],
 [1330, 2209, 3277, 4745, 266, 1311, 4853, 5590, 3401, 7285, 2431, 1613],
 [2905, 7287, 3995, 5106, 549, 1454, 3995, 9453, 6181],
 [1646, 8791, 1330, 8417, 9726, 1703, 8684, 6785, 3735, 2711, 8201, 2476],
 [5339, 2466, 6024, 2697, 4557, 3346, 2642, 279],
 [499, 9202, 8819, 1487, 7554, 937, 1146],
 [2184, 3975, 1511, 4911, 8494, 7285, 8947, 9033, 396],
 [697, 6210, 7285, 9693, 8796, 868, 6501],
 [2470, 6230, 7661, 6216, 7656, 9327, 7345, 5694],
 [1003, 3968, 998, 3157, 5115, 9263, 9352, 802, 2402],
 [7285, 9526, 9202, 2553, 5036, 2396, 8941, 2553, 283],
 [8900, 9173, 7285, 7618, 3008, 9345, 497, 998, 7617, 3221],
 [7620, 7684, 3543, 5065, 9199, 9472, 7702, 9138, 2505, 164],
 [5822, 3975, 745, 5004, 8638, 6485, 820, 9141, 1475, 5989, 3975, 9817, 113],
 [6172, 5082, 5799, 7607, 4245, 6004, 9160],
 [5250, 1703, 1487, 6409, 7285, 4584, 2520, 7212, 1613],
 [6588, 8520, 918, 5320, 367, 8848, 4492, 8575],
 [2470, 866, 4460, 4895, 9839, 4473, 6670, 6750],
 [2380, 9278, 4792, 1487, 9451, 6861, 8947, 2470, 2032, 1613],
 [6072, 7179, 3093, 1297, 9415, 1589, 4882, 6626],
 [8524, 6670, 7738, 5136, 9469, 9693, 7285, 5329, 3503, 224, 1613],
 [7285, 3923, 6072, 500, 6159, 8759, 6626],
 [3381, 1327, 3581, 3076, 8331, 9118, 5723, 2120, 3290, 9310, 5837, 1613],
 [2744, 7167, 4877, 3497, 5115, 8131],
 [534, 2160, 8331, 3401, 6546, 6072, 6409, 7285],
 [9296, 6903, 4264, 534, 4320, 6154, 5354, 3928, 789],
 [6841, 7056, 355, 3572, 3735, 6283, 2184, 1311, 5626, 1613],
 [8331, 1872, 6628, 1274, 1819, 7622, 5282, 1024, 2865],
 [8331, 918, 6892, 8400, 756, 1562, 2580, 1014, 8741, 5919],
 [5817, 1613, 8152, 2470, 9748, 9170, 3578, 9276, 7096, 7212],
 [102, 6186, 9817, 4626, 2079, 7492, 3872, 1154, 9937, 8244],
 [6072, 1487, 6604, 4604, 8741, 9563, 907, 9258, 6988],
 [7884, 679, 7673, 4774, 2825, 266, 2239, 6001, 2350],
 [8331, 907, 8624, 6873, 9415, 7159, 177, 3143, 8208],
 [9328, 9586, 7696, 1311, 3052, 9547, 6007, 7285],
 [2905, 1487, 8331, 3995, 8353, 4791, 9453, 6181],
 [5989, 6751, 3499, 3030, 9748, 8715, 6154, 2884, 2130],
 [2209,
  3277,
  5626,
  1157,
  6077,
  8636,
  6776,
  8678,
  5590,
  6072,
  9169,
  49,
  2932,
  9726,
  3277,
  7528,
  5846,
  4766,
  1613],
 [7056, 5992, 3008, 3170, 5764, 4063, 7040, 998, 6559, 7196, 6431],
 [8796, 9081, 2580, 2144, 5733, 739, 5568, 1487, 8014, 3401, 2131],
 [6072, 5659, 8131, 6396, 971, 9908, 1470],
 [2403, 7946, 464, 9715, 918, 1050, 5192, 5687, 866, 3141],
 [7285, 8768, 7618, 7196, 485, 7450, 7342, 6489, 79],
 [8809, 163, 9371, 1088, 9451, 4116, 4504, 9169, 1571, 5822, 9472, 79],
 [5687, 1487, 5320, 3438, 6588, 6959],
 [2884, 2032, 7542, 5329, 6088, 9170, 5843, 8900, 7159, 1936],
 [6493, 3208, 1487, 6617, 7921, 5968, 4974, 5241, 234, 8784],
 [8912, 3975, 5214, 1487, 2697, 6961, 9636, 3460, 9415],
 [7948, 8474, 3967, 7285, 534, 4358, 3939, 7878, 6750, 7285, 470, 6790],
 [7185, 1487, 985, 2394, 6351, 5153, 2394, 918, 9290, 1532, 7370],
 [2538, 2697, 9547, 7285, 15, 4691, 2476],
 [9850,
  8528,
  5865,
  9388,
  6181,
  7555,
  4883,
  4962,
  7908,
  7463,
  6072,
  470,
  9700,
  3924,
  96],
 [9490, 8792, 9900, 4424, 4670, 6709, 2763, 6227, 396, 5193, 1613],
 [5713, 8425, 3771, 1703, 4089, 4393, 2300, 9296, 2268],
 [9202, 6231, 8527, 4577, 8331, 6468, 5188],
 [1813, 7656, 820, 9383, 7177, 2476, 8331, 1613],
 [4557, 2130, 2278, 584, 9578, 8014, 3401],
 [637, 108, 1275, 9159, 5636, 8581, 8331, 5378, 1487],
 [2517,
  4784,
  5846,
  2189,
  4245,
  8244,
  7736,
  2130,
  3401,
  2470,
  6670,
  8214,
  1613],
 [7285, 5241, 7406, 6651, 3995, 9453, 6181, 2865],
 [7691, 8724, 7400, 8184, 4969, 542, 7676, 5435, 5626, 1481, 3670],
 [5674, 5436, 1157, 6606, 2711],
 [4910, 5320, 8331, 3975, 2184, 9472, 2850, 9415],
 [1512, 7350, 918, 7285, 8756, 3277, 9121, 1613],
 [3973, 6514, 1353, 72, 3825, 1907, 5602],
 [8331, 4492, 9281, 7285, 8614, 1019, 829, 3352],
 [799, 9358, 998, 1487, 2795, 1857, 4620, 5990, 1016, 2697],
 [9281, 5019, 7285, 1352, 9798, 8331, 823, 2825, 1507, 4637],
 [9425, 3178, 2470, 6051, 6904, 4089],
 [1613, 200, 2470, 9748, 4089, 9909, 3288, 1927, 4503],
 [4092, 9563, 7285, 8715, 6283, 7656, 3771, 9173, 7212, 7297, 1613],
 [4495, 8320, 6898, 533, 7285, 3016, 8638, 8684, 9169, 1571],
 [8825, 7908, 4424, 5752, 7185, 9713, 7678, 7710],
 [9406, 5320, 9227, 594, 3401],
 [7738, 2711, 299, 4413, 3060, 1613],
 [2209,
  3581,
  1024,
  7285,
  7212,
  5265,
  3647,
  4975,
  7656,
  4682,
  3604,
  6959,
  1613],
 [6072, 2035, 7466, 2218, 6657, 8154, 9563, 907],
 [5563, 7739, 7675, 5574, 6072, 5848, 771, 4579, 9584, 5590, 3606, 1613],
 [7285,
  8715,
  6431,
  7171,
  9853,
  3278,
  9613,
  3967,
  2004,
  1274,
  8400,
  7525,
  1613],
 [5603, 3755, 328, 6363, 3732, 6892, 3073, 3755, 8534, 7675, 8214, 7738],
 [9406, 6975, 3290, 2629, 869, 5454, 7762, 7734, 3401],
 [3647, 4370, 1330, 1490, 7656, 4682, 3604, 996, 2127, 3499, 9613, 4379, 9770],
 [2184, 2209, 7285, 485, 6591, 9829, 3581, 9196, 2132, 9170, 3654],
 [3008,
  6453,
  7947,
  1857,
  4212,
  7432,
  798,
  5001,
  9661,
  4080,
  3277,
  6422,
  4620,
  9661,
  6191,
  6007,
  182,
  1613],
 [542, 8263, 3157, 9588, 9210, 1050, 7285, 5281, 4455, 8287, 3771],
 [4080, 7763, 8093, 9565, 2352, 5523, 7285, 5859, 7584, 3165, 209, 9565, 19],
 [7285, 2825, 1397, 8416, 2034, 9023, 9170, 1613],
 [2470, 2032, 745, 9436, 8846, 6167, 3503, 4132, 9563, 2311],
 [8138, 3008, 2580, 3975, 9388, 1627, 3967, 4267, 8520, 783, 339],
 [8912, 3975, 2119, 7285, 534, 6133, 6961, 8895],
 [1419,
  5532,
  9415,
  1422,
  981,
  1259,
  8207,
  1397,
  3581,
  8004,
  1422,
  981,
  591,
  4911,
  1541,
  8124,
  2239,
  1353,
  9263,
  5661],
 [6072,
  5989,
  8775,
  2884,
  113,
  5574,
  6146,
  6227,
  1157,
  2119,
  9563,
  3647,
  7656,
  6959,
  7723],
 [867, 1849, 5135, 7842, 6535, 5764, 1514],
 [9150, 209, 798, 5989, 6751, 3499, 5159, 3917, 367, 8848, 1613],
 [1016, 9472, 7285, 7734, 1762, 4325],
 [4885, 8331, 8786, 113, 4532, 6432, 5989, 8936, 8208],
 [7285, 9748, 3919, 4723, 9998, 3044, 7463, 1050, 2032, 8671, 4484],
 [2117,
  8912,
  1880,
  4942,
  1006,
  5659,
  2736,
  5436,
  6865,
  9390,
  3288,
  7762,
  1150,
  9521,
  8156,
  7285,
  7734,
  1613],
 [2032, 7542, 9817, 6652, 5082, 7771, 3637, 2821],
 [7285, 1450, 200, 679, 6474, 8131],
 [8331, 9118, 5723, 56, 1310, 6873, 1936, 6206, 9261, 5719, 5903],
 [2665, 8520, 9526, 8903, 8803, 2755, 4049],
 [3431, 466, 1473, 9821, 5764, 7285, 7212, 7335],
 [1613, 9853, 8663, 6072, 1693, 7635, 6490, 9214, 6499, 7849, 9412, 3321],
 [6286, 8287, 5320, 56, 3401],
 [8331, 4626, 8353, 8761, 3655, 1819, 7622],
 [3352, 9309, 6588, 3840, 8818, 7285, 2893],
 [2350,
  7056,
  5916,
  9549,
  5975,
  5128,
  3864,
  3647,
  3581,
  4723,
  9998,
  8520,
  1613],
 [7285, 1352, 9169, 7816, 1819, 7622, 2517, 7526, 7297, 7622, 9976],
 [5555, 7285, 3157, 1633, 7168, 1579, 5596, 2239, 5626, 7196],
 [8231, 6670, 9081, 1998, 9883, 1990, 3141],
 [3331, 3222, 594, 6802, 2254, 7370, 645, 5816, 6701],
 [7285, 7072, 4125, 8300, 5590, 7168, 6822, 4277, 2825, 519, 7166],
 [3857, 4552, 1454, 8331, 4037, 4156, 9202, 1052, 7036],
 [3834, 7842, 4265, 4991, 7630, 5989, 2200, 7022, 2361, 8423],
 [4877, 1813, 8152, 4774, 2825, 4786, 4615],
 [2075, 5019, 7125, 8520, 5493, 177, 5937, 1872, 7285],
 [3975, 8770, 1487, 1454, 2850, 9415, 7963, 3328],
 [3347, 8331, 2726, 5723, 5630, 8784, 918, 5529, 5152],
 [7167, 1487, 7285, 2350, 4791, 2884, 2905, 5329],
 [9563, 907, 4620, 1163, 1813, 3776, 7569, 1077],
 [283, 2580, 1002, 2825, 2865, 8331, 5453],
 [8912,
  7732,
  4878,
  7177,
  5250,
  1115,
  5530,
  3967,
  349,
  5250,
  5003,
  8320,
  56,
  7450,
  985,
  3143],
 [2470, 2032, 8524, 9296, 9825, 1613],
 [2649, 6750, 1487, 7297, 7185, 8197, 257, 5847, 299, 5622],
 [823, 3768, 3952, 6186, 9415, 789, 8670, 8223, 2682, 3581, 4181, 3076, 7027],
 [3302, 8819, 7737, 3964, 2612, 5192, 303],
 [8903, 3454, 9415, 8121, 7036, 2580, 460],
 [3670, 6558, 2726, 2893, 799, 8756, 7285, 6645, 1483, 492, 430, 2396],
 [6080, 177, 7561, 5805, 6875, 2697, 2489, 200],
 [7314, 4686, 8848, 8715, 5128, 7285],
 [7907,
  1209,
  1327,
  1487,
  7285,
  7561,
  7954,
  2697,
  2200,
  2470,
  7561,
  6750,
  4966,
  1613],
 [7168,
  5881,
  9790,
  2987,
  6283,
  7675,
  5193,
  8662,
  8613,
  3320,
  5129,
  5764,
  2987,
  6283,
  4455,
  2251,
  7056],
 [9202, 8331, 5630, 5329, 1352, 2538, 6802, 3753, 6796, 200],
 [5027, 7096, 1157, 2580, 2545, 499, 7635],
 [499, 937, 9212, 4277, 8715, 2053, 3141],
 [2580, 7837, 5269, 2032, 8650, 5461, 9563, 907, 4661, 5269, 448, 985],
 [9202, 2726, 2013, 9259, 8432, 4136, 5192, 303, 8208],
 [3008, 9202, 2629, 5989, 3876, 8562, 4788, 7734, 7285, 2697, 6165, 7561],
 [907, 2697, 789, 9093, 7450, 6382, 8900],
 [6072, 795, 1873, 8331, 2538, 9748, 2032],
 [1646, 2884, 5809, 8487, 4228, 6456, 6004, 929],
 [9415, 6343, 3732, 1720, 7285, 3637, 6626, 4620, 9585, 9170, 1033, 1613],
 [7285, 9281, 4063, 2612, 8724, 6412, 3581],
 [2184, 5850, 9487, 2032, 1533, 724, 1684, 9212, 4228],
 [4656, 5741, 7147, 6989, 9547, 8562, 8715, 1267, 842],
 [820, 3515, 985, 9829, 3698, 9451, 5860],
 [7285, 2825, 6474, 6989, 3439, 3143, 3952, 8507, 9563, 907],
 [6637, 6750, 7179, 8810, 9847, 9415, 200],
 [7297, 6815, 8715, 9453, 6652, 6181, 7736, 177, 4047, 113],
 [8848, 4620, 1546, 4393, 6776, 7285, 8724, 5989, 7800, 7116, 9748],
 [1939, 4079, 300, 8510, 7554, 8591, 9451, 3407, 3454, 6072, 1613],
 [7674, 4730, 7408, 4626, 4730, 8541, 5885, 8033],
 [7285, 6432, 7185, 8601, 5916, 6330, 3553, 3655],
 [6072, 6409, 7285, 534, 2160, 6546, 3401, 8756],
 [9415, 3541, 7156, 5855, 5626, 3008, 939, 6789, 6382, 1248, 2144, 5687],
 [7185, 5574, 8594, 5302, 3637, 9994, 200],
 [6712, 9118, 5723, 7355, 4448, 6393, 9279, 6799],
 [6500, 6781, 7691, 200, 6558, 8837, 7285, 6334, 3056, 9748, 4504, 1613],
 [6007, 6055, 5989, 6751, 3141, 6133, 1819, 7622, 1454, 3567, 2966],
 [4670, 6763, 6850, 6549, 998, 5981, 6409, 2489, 7545],
 [6072, 1487, 7185, 266, 866, 5713, 8331, 6626, 6831, 4633],
 [6024, 560, 8520, 4075, 6661, 55, 7797, 7607],
 [5320, 8624, 4075, 1013, 4612, 2674, 9472],
 [8796, 5674, 1813, 2744, 9365, 6215, 5630, 6072, 6389, 1613],
 [8331, 7177, 283, 9547, 6072, 6154, 3075, 4994],
 [6512, 3924, 9024, 2470, 1559, 5590, 3968, 6044, 1613],
 [6796, 4803, 5626, 519, 3278, 5723, 6216, 4505, 907, 9197, 7585, 9900, 6199],
 [7584, 3707, 830, 6709, 8331, 823, 6199, 5462, 7564],
 [2184, 560, 9572, 4970, 464, 6750, 7285, 7097, 3401],
 [8809, 1699, 3073, 7738, 196, 6133, 1760, 9563, 479, 6419],
 [9310, 2996, 3857, 1790, 8320, 1050, 8933, 3857, 3581, 9327],
 [8331, 4264, 3029, 1490, 3076, 7285, 7106, 3499, 2893],

Embedding Representation

In [38]:
sent_length = 20
embedded_docs = pad_sequences(one_hot_repr, padding='pre' , maxlen=sent_length)
embedded_docs

array([[   0,    0,    0, ..., 2979, 4162, 2979],
       [   0,    0,    0, ..., 9169,   49, 9182],
       [   0,    0,    0, ..., 6852, 8171, 7452],
       ...,
       [   0,    0,    0, ..., 7166, 2328, 6181],
       [   0,    0,    0, ..., 6078, 3352, 1508],
       [   0,    0,    0, ..., 3578, 6146, 8900]],
      shape=(44898, 20), dtype=int32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense

model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(voc_size, 40),
    Bidirectional(LSTM(100,
        dropout=0.3,
        recurrent_dropout=0.3)),  
    Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 40)         │       400,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 200)            │       112,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513,001 (1.96 MB)

 Trainable params: 513,001 (1.96 MB)

 Non-trainable params: 0 (0.00 B)

In [40]:
len(embedded_docs), Y.shape

(44898, (44898,))

In [41]:
import numpy as np
X_final = np.array(embedded_docs)
Y_final = np.array(Y)

In [42]:
X_final.shape, Y_final.shape

((44898, 20), (44898,))

In [43]:
from sklearn.model_selection import train_test_split

X_train , X_test , Y_train , Y_test = train_test_split(X_final, Y_final, test_size=0.2, random_state=42)

In [44]:
## Model traning 
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=10, batch_size=62)

Epoch 1/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 57s 60ms/step - accuracy: 0.9089 - loss: 0.2148 - val_accuracy: 0.9516 - val_loss: 0.1301
Epoch 2/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 34s 58ms/step - accuracy: 0.9572 - loss: 0.1158 - val_accuracy: 0.9509 - val_loss: 0.1252
Epoch 3/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 33s 57ms/step - accuracy: 0.9672 - loss: 0.0904 - val_accuracy: 0.9547 - val_loss: 0.1206
Epoch 4/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 34s 58ms/step - accuracy: 0.9748 - loss: 0.0697 - val_accuracy: 0.9533 - val_loss: 0.1231
Epoch 5/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 33s 57ms/step - accuracy: 0.9779 - loss: 0.0591 - val_accuracy: 0.9529 - val_loss: 0.1469
Epoch 6/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 33s 57ms/step - accuracy: 0.9832 - loss: 0.0488 - val_accuracy: 0.9527 - val_loss: 0.1456
Epoch 7/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 34s 58ms/step - accuracy: 0.9858 - loss: 0.0390 - val_accuracy: 0.9507 - val_loss: 0.1721
Epoch 8/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 33s 57ms/step - accuracy: 0.9880 - loss: 0.0341 - val_accuracy: 0.9474 - val_loss: 0.1799
Epoch 9/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 33s 57ms/step - accuracy: 0.9900 - loss: 0.0292 - val_accuracy: 0.9517 - val_loss: 0.1917
Epoch 10/10
580/580 ━━━━━━━━━━━━━━━━━━━━ 31s 54ms/step - accuracy: 0.9912 - loss: 0.0246 - val_accuracy: 0.9489 - val_loss: 0.2025

In [45]:
y_pred = model.predict(X_test)

281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step

In [46]:
y_pred = np.where(y_pred > 0.5,1,0)

In [47]:
from sklearn.metrics import confusion_matrix

In [48]:
confusion_matrix(Y_test, y_pred)

array([[4488,  222],
       [ 237, 4033]])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred)

0.9488864142538975

In [50]:
from sklearn.metrics import classification_report
print(classification_report(Y_test , y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      4710
           1       0.95      0.94      0.95      4270

    accuracy                           0.95      8980
   macro avg       0.95      0.95      0.95      8980
weighted avg       0.95      0.95      0.95      8980